### ISSUE TITLE
pull requests?

### ISSUE THREAD

**Issue by glidej** [Biuni/PokemonGO-Pokedex#1]
I'd like to create a pull request to add a package.json to the project. Could you open this project up for contributions?

**Comment by Biuni** [comment]
I added you. Now you are a collaborator.

**Comment by Biuni** [comment]
You could help me with the correcting english on the README?

**Comment by glidej** [comment]
Sure! I will have some time this afternoon (EST) to look. I'll submit a pull request with changes.

**Comment by Biuni** [comment]
Thanks a lot! :+1:
