### ISSUE TITLE
Multipliers

### ISSUE THREAD

**Issue by elincognito** [Biuni/PokemonGO-Pokedex#15]
Multipliers should always be a json array, and not a depend on either the pokemon has  "max", "min", or just a single value.
This way complicates json deserialization.

Suggestion:
```
multipliers: 1.58 becomes 
multipliers: [1.58]
```

**Comment by Biuni** [comment]
Thanks for the suggestion but I don't have more time to follow the project. Please, send me a Pull Request with the changes.

**Comment by Biuni** [comment]
I did it!
