### ISSUE TITLE
improvment : could rarity be added ? common/legendary/epic ?

### ISSUE THREAD

**Issue by cpainchaud** [Biuni/PokemonGO-Pokedex#8]
thx !

**Comment by Biuni** [comment]
Can you show me official rarity for each Pokémon?

**Comment by RedSparr0w** [comment]
Closest thing would probably be [this](http://pokemongohub.net/pokemon-go-spawn-rate/)

But then again im pretty sure some pokemon are rare in 1 area compared to another.

Could probably be split up into basic rarities though.

example based on [above linked page](http://pokemongohub.net/pokemon-go-spawn-rate/)

| Rarity | Min Spawn Chance |
| :-: | :-: |
| Common | 2% |
| Uncommon | 0.5% |
| Rare | 0.05% |
| Legendary | 0.005% |
| Epic | 0% |

**Comment by Biuni** [comment]
Added 3 new fields!

**Comment by Biuni** [comment]
Added 3 new fields! Can you help me with the explanation of this fields on README? Send me a Pull Request with the correct README. Thanks a lot!

**Comment by RedSparr0w** [comment]
The descriptions you have written look pretty good already [=

**Comment by Biuni** [comment]
Ok. Close :)
